// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: files.v1.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceType int32

const (
	ReferenceType_UNASSIGNED  ReferenceType = 0
	ReferenceType_TRANSACTION ReferenceType = 1
	ReferenceType_CHANNEL     ReferenceType = 2
	ReferenceType_GENERIC     ReferenceType = 3
)

// Enum value maps for ReferenceType.
var (
	ReferenceType_name = map[int32]string{
		0: "UNASSIGNED",
		1: "TRANSACTION",
		2: "CHANNEL",
		3: "GENERIC",
	}
	ReferenceType_value = map[string]int32{
		"UNASSIGNED":  0,
		"TRANSACTION": 1,
		"CHANNEL":     2,
		"GENERIC":     3,
	}
)

func (x ReferenceType) Enum() *ReferenceType {
	p := new(ReferenceType)
	*p = x
	return p
}

func (x ReferenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_files_v1_proto_enumTypes[0].Descriptor()
}

func (ReferenceType) Type() protoreflect.EnumType {
	return &file_files_v1_proto_enumTypes[0]
}

func (x ReferenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceType.Descriptor instead.
func (ReferenceType) EnumDescriptor() ([]byte, []int) {
	return file_files_v1_proto_rawDescGZIP(), []int{0}
}

type FileReferenceProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     ReferenceType `protobuf:"varint,1,opt,name=type,proto3,enum=files.ReferenceType" json:"type,omitempty"`
	Id       int32         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	EntityId string        `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *FileReferenceProto) Reset() {
	*x = FileReferenceProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_files_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReferenceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReferenceProto) ProtoMessage() {}

func (x *FileReferenceProto) ProtoReflect() protoreflect.Message {
	mi := &file_files_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReferenceProto.ProtoReflect.Descriptor instead.
func (*FileReferenceProto) Descriptor() ([]byte, []int) {
	return file_files_v1_proto_rawDescGZIP(), []int{0}
}

func (x *FileReferenceProto) GetType() ReferenceType {
	if x != nil {
		return x.Type
	}
	return ReferenceType_UNASSIGNED
}

func (x *FileReferenceProto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileReferenceProto) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type FileMetadataProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId          int32               `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Name            string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MimeType        string              `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes       int64               `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAtUnixMs int64               `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64               `protobuf:"varint,6,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	CreatedBy       string              `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Thumbnail       []byte              `protobuf:"bytes,8,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Reference       *FileReferenceProto `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *FileMetadataProto) Reset() {
	*x = FileMetadataProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_files_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataProto) ProtoMessage() {}

func (x *FileMetadataProto) ProtoReflect() protoreflect.Message {
	mi := &file_files_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataProto.ProtoReflect.Descriptor instead.
func (*FileMetadataProto) Descriptor() ([]byte, []int) {
	return file_files_v1_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadataProto) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileMetadataProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadataProto) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMetadataProto) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadataProto) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *FileMetadataProto) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *FileMetadataProto) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *FileMetadataProto) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *FileMetadataProto) GetReference() *FileReferenceProto {
	if x != nil {
		return x.Reference
	}
	return nil
}

type FilesCatalogProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaMinorVersion   int32                `protobuf:"varint,1,opt,name=schema_minor_version,json=schemaMinorVersion,proto3" json:"schema_minor_version,omitempty"`
	LastModifiedByCommit string               `protobuf:"bytes,2,opt,name=last_modified_by_commit,json=lastModifiedByCommit,proto3" json:"last_modified_by_commit,omitempty"`
	Files                []*FileMetadataProto `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *FilesCatalogProto) Reset() {
	*x = FilesCatalogProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_files_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesCatalogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesCatalogProto) ProtoMessage() {}

func (x *FilesCatalogProto) ProtoReflect() protoreflect.Message {
	mi := &file_files_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesCatalogProto.ProtoReflect.Descriptor instead.
func (*FilesCatalogProto) Descriptor() ([]byte, []int) {
	return file_files_v1_proto_rawDescGZIP(), []int{2}
}

func (x *FilesCatalogProto) GetSchemaMinorVersion() int32 {
	if x != nil {
		return x.SchemaMinorVersion
	}
	return 0
}

func (x *FilesCatalogProto) GetLastModifiedByCommit() string {
	if x != nil {
		return x.LastModifiedByCommit
	}
	return ""
}

func (x *FilesCatalogProto) GetFiles() []*FileMetadataProto {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_files_v1_proto protoreflect.FileDescriptor

var file_files_v1_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x22, 0xcc, 0x02, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73,
	0x12, 0x2b, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75,
	0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x37, 0x0a, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x5f, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4d,
	0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x17, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6c, 0x61,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2a, 0x4a, 0x0a, 0x0d, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x4e, 0x41, 0x53, 0x53, 0x49, 0x47, 0x4e, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43, 0x10, 0x03, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6e,
	0x67, 0x64, 0x61, 0x68, 0x6c, 0x2f, 0x67, 0x6f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_files_v1_proto_rawDescOnce sync.Once
	file_files_v1_proto_rawDescData = file_files_v1_proto_rawDesc
)

func file_files_v1_proto_rawDescGZIP() []byte {
	file_files_v1_proto_rawDescOnce.Do(func() {
		file_files_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_files_v1_proto_rawDescData)
	})
	return file_files_v1_proto_rawDescData
}

var file_files_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_files_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_files_v1_proto_goTypes = []interface{}{
	(ReferenceType)(0),         // 0: files.ReferenceType
	(*FileReferenceProto)(nil), // 1: files.FileReferenceProto
	(*FileMetadataProto)(nil),  // 2: files.FileMetadataProto
	(*FilesCatalogProto)(nil),  // 3: files.FilesCatalogProto
}
var file_files_v1_proto_depIdxs = []int32{
	0, // 0: files.FileReferenceProto.type:type_name -> files.ReferenceType
	1, // 1: files.FileMetadataProto.reference:type_name -> files.FileReferenceProto
	2, // 2: files.FilesCatalogProto.files:type_name -> files.FileMetadataProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_files_v1_proto_init() }
func file_files_v1_proto_init() {
	if File_files_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_files_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReferenceProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_files_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetadataProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_files_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesCatalogProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_files_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_files_v1_proto_goTypes,
		DependencyIndexes: file_files_v1_proto_depIdxs,
		EnumInfos:         file_files_v1_proto_enumTypes,
		MessageInfos:      file_files_v1_proto_msgTypes,
	}.Build()
	File_files_v1_proto = out.File
	file_files_v1_proto_rawDesc = nil
	file_files_v1_proto_goTypes = nil
	file_files_v1_proto_depIdxs = nil
}
